version: "2"
services:
  web:
    image: odoo:${ODOO_VERSION}
    restart: always
    container_name: ${INSTANCE}
    hostname: ${INSTANCE}
    depends_on:
      - db
    volumes:
      - web-data:/var/lib/odoo
      - config:/etc/odoo
      - extra-addons:/mnt/extra-addons
      - backups:/mnt/backups
      # TODO sites-packages
    environment:
      - VIRTUAL_HOST=${DOMAIN},www.${DOMAIN},farma.${DOMAIN},test.${DOMAIN},seasons.${DOMAIN}
      - VIRTUAL_PORT=8069
      - LETSENCRYPT_HOST=${DOMAIN},www.${DOMAIN},test.${DOMAIN},seasons.${DOMAIN}
      - LETSENCRYPT_EMAIL=${CONTACT}
    networks:
      - nginx-proxy
      - internal

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: ${INSTANCE}_db
    hostname: ${INSTANCE}_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  web-data:
  config:
  extra-addons:
  backups:
  db-data:
  site-packages3.7:
  site-packages2.7:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  internal:
    external: false
